name: Increment version of updated languages

on:
  push:
    branches: [ matrix ]
    paths:
      - '**resource.language.**strings.po'
      - '**resource.language.**langinfo.xml'

jobs:
  default:
    runs-on: ubuntu-latest
    name: Increment version of updated languages

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ${{ github.event.repository.name }}

      - name: Checkout Scripts
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: xbmc/weblate-supplementary-scripts
          path: scripts

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Get changed files
        uses: trilom/file-changes-action@v1.2.4

      - name: Increment version of updated languages
        run: |
          python3 ../scripts/repo-resources/increment_version.py $HOME/files.json
        working-directory: ${{ github.event.repository.name }}

      - name: Create PR for incremented versions
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          commit-message: Language add-on versions incremented
          title: Language add-on versions incremented
          body: Language add-on versions incrementing triggered by ${{ github.sha }}
          branch: inc-ver
          delete-branch: true
          path: ./${{ github.event.repository.name }}